import type { DictationSession } from './contracts.js'
import {
  defaultInsertionPlan,
  defaultSettings,
  emptyContextSnapshot,
} from './defaults.js'

export const createTestSession = (
  overrides: Partial<DictationSession> = {},
): DictationSession => ({
  _id: 'dictationSessions:test' as DictationSession['_id'],
  _creationTime: 1,
  sessionId: 'session-test',
  isActive: false,
  activationMode: 'toggle',
  status: 'cancelled',
  captureIntent: 'none',
  startedAt: new Date().toISOString(),
  finishedAt: new Date().toISOString(),
  processingStartedAt: null,
  targetApp: 'App',
  context: emptyContextSnapshot,
  partialText: '',
  finalText: '',
  insertionPlan: defaultInsertionPlan,
  errorMessage: null,
  noticeMessage: null,
  timing: {
    sessionStartedMs: 0,
    contextPreviewStartedMs: null,
    contextPreviewCompletedMs: null,
    contextRefreshStartedMs: null,
    contextRefreshCompletedMs: null,
    submissionStartedMs: null,
    stopRequestedMs: null,
    microphoneRequestStartedMs: null,
    microphoneRequestCompletedMs: null,
    recordingStartedMs: null,
    recordingEndedMs: null,
    recorderStopStartedMs: null,
    mediaRecorderStopCompletedMs: null,
    audioPreparationStartedMs: null,
    audioPreparationEndedMs: null,
    processingStartedMs: null,
    llmRequestStartedMs: null,
    llmResponseHeadersMs: null,
    firstTokenMs: null,
    llmCompletedMs: null,
    insertionStartedMs: null,
    insertionCompletedMs: null,
    sessionFinishedMs: null,
  },
  audio: {
    durationMs: 0,
    mimeType: null,
    bytes: 0,
    speechDetected: false,
    peakAmplitude: 0,
    rmsAmplitude: 0,
    languageHint: null,
    stopReason: 'unknown',
    maxDurationReached: false,
  },
  llm: {
    provider: 'openrouter',
    modelId: defaultSettings.modelId,
    finishReason: null,
    usedContext: false,
  },
  insertion: {
    strategy: 'insert-at-cursor',
    requestedMode: 'letter-by-letter',
    effectiveMode: 'letter-by-letter',
    method: 'clipboard-all-at-once',
    fallbackUsed: false,
    targetApp: 'App',
    writtenCharacterCount: null,
  },
  historyStatus: 'not-required',
  historyError: null,
  createdAtMs: 0,
  updatedAtMs: 0,
  ...overrides,
})
